
CREATE TABLE public.student_information (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  middle_name TEXT,
  date_of_birth DATE,
  age INTEGER,
  place_of_birth TEXT,
  gender TEXT,
  civil_status TEXT,
  spouse_name TEXT,
  nationality TEXT,
  religion TEXT,
  tribe TEXT,
  vaccination_status TEXT,
  date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  address TEXT,
  current_address TEXT,
  contact TEXT,
  facebook_link TEXT,
  parent_guardian TEXT,
  parent_guardian_relation TEXT,
  parent_guardian_address TEXT,
  parent_guardian_contact TEXT,
  sec_parent_guardian TEXT,
  sec_parent_guardian_relation TEXT,
  sec_parent_guardian_address TEXT,
  sec_parent_guardian_contact TEXT,
  father_first_name TEXT,
  father_middle_name TEXT,
  father_last_name TEXT,
  father_name TEXT,
  father_occupation TEXT,
  father_contact TEXT,
  mother_first_name TEXT,
  mother_middle_name TEXT,
  mother_last_name TEXT,
  mother_name TEXT,
  mother_occupation TEXT,
  mother_contact TEXT,
  parent_marital_status TEXT,
  income_sources TEXT,
  other_income TEXT,
  monthly_income NUMERIC,
  student_lrn TEXT,
  department TEXT,
  shs_track TEXT,
  elem_school TEXT,
  elem_address TEXT,
  elem_year TEXT,
  sec_school TEXT,
  sec_address TEXT,
  sec_year TEXT,
  last_school TEXT,
  last_school_address TEXT,
  last_school_year TEXT,
  course TEXT,
  year_level TEXT
);

ALTER TABLE public.student_information ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert" ON public.student_information FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated read" ON public.student_information FOR SELECT TO authenticated USING (true);
