// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhoeozspoinjzcmfkzoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhob2VvenNwb2luanpjbWZrem9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyOTIwMTcsImV4cCI6MjA4Njg2ODAxN30.AlblnOcGOiwBnxK3C3MzA3Xfg31l-ES-vfK5Sfc1QlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});